# Generated by Django 5.0.4 on 2024-04-13 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tutorrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingjob',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(default=[])),
                ('ongoingjob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ongoingjob')),
            ],
        ),
    ]
