# Generated by Django 5.0.4 on 2024-04-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ongoingjob_start_date_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='ongoingjob',
            field=models.IntegerField(null=True),
        ),
    ]
