# Generated by Django 5.0.4 on 2024-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_rename_profile_image_tutor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.CharField(default='All', max_length=100),
        ),
    ]
